services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      frontend:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # # Example for a database like PostgreSQL
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password
  #     POSTGRES_DB: startupscope
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "your_user"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
