[project]
name = "startupscope-backend"
version = "0.1.0"

dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "sqlalchemy",
  "pydantic",
  "sqlmodel"
]

[build-system]
requires = ["uv-pip"]
build-backend = "uv-pip"


